### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by root-11** [root-11/root-11.github.io#2]
- [ ] Solve byzantine generals problem using mutual adjustment.
- [ ] Resource constrained project scheduling problem
- [ ] Capacitated vehicle routing problem with time windows (CVRPTW)
- [ ] capacitated vehicle routing problem (CVRP)
- [ ] Capacitated vehicle routing problem (CVRP, large datasets)
- [ ] Pickup and Delivery with Time Windows (PDPTW) 
- [ ] Maintenance scheduling problem
- [ ] Car sequencing problem with paint-shop batching constraints
- [ ] Simple assembly line balancing problem (SALBP)
- [ ] Quadrative assignment problem (QAP)
- [ ] Traveling salesman's problem (TSP)
- [ ] K-Means clustering problems (MSSC)
- [ ] Bin packing problem (BPP).
- [ ] Knapsack problem
- [ ] Facility location problem (FLP)
- [ ] Capacitated facility location problem (CFLP)
- [ ] Portfolio Selection Optimization Problem
- [ ] Flow Shop Sequencing problem
- [ ] Flexible job shop scheduling problem
- [ ] Flexible job shop scheduling problem with setup times
- [ ] Flexible job shop scheduling problem (with intensity)
- [ ] Stochastic job shop scheduling problem
- [ ] Aircraft Landing problem
